export const ActionTypes = {
  FETCH_POKEMONS_START: 'FETCH_POKEMONS_START',
  FETCH_POKEMONS_SUCCESS: 'FETCH_POKEMONS_SUCCESS',
  FETCH_POKEMONS_FAILURE: 'FETCH_POKEMONS_FAILURE',
  ADD_POKEMON: 'ADD_POKEMON',
  DELETE_POKEMON: 'DELETE_POKEMON',
} as const;
